
name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Install Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with maven
        run: mvn -B package --file pom.xml

      
    
